#!/usr/bin/env nextflow

help_message = """
E X S C A N   P I P E L I N E
=============================
Exploration and annotation of exons and their features using profile HMMs.

Usage:
    nextflow run exscan.nf --fasta <fasta> --hmmdb <hmm_db>
    nextflow run exscan.nf -params-file <yaml>

Required Arguments:
    --fasta <fasta>           : Input fasta file
    --hmmdb <hmmdb>           : Profile HMM database file
                                Index files from hmmpress must also be located in the same directory

Alternative to Required Arguments:
    -params-file <yaml>       : YAML/JSON file with parameters for each sample
                                Mutually exclusive with --fasta and --hmmdb

Optional Arguments:
    --dom_ieval <val>         : Domain alignment individual e-value filter [default: ${params.dom_ieval}]
                                Domain alignments with **EQUAL OR LESS** than this e-value will be kept
    --fasta_type <val>        : Type of sequences found in input `--fasta` file.
                                Choices: {dna, rna, protein} [defalut: $params.fasta_type]
    --group_distance <val>    : Group query results within n bps [default: ${params.group_distance}]
    --min_alignment_len <val> : Domain alignment minimum lenght filter [default: ${params.min_alignment_len}]
                                Domain alignments with **EQUAL OR MORE** than this distance will be
    --outdir <outdir>         : Output directory [default: ${params.outdir}]

    --help                    : Print help message and exit
    --version                 : Print version and exit
"""

init_summary = """
E X S C A N   P I P E L I N E   v${params.manifest.version}
======================================
fasta             : ${params.fasta}
hmmdb             : ${params.hmmdb}
dom_ieval         : ${params.dom_ieval}
fasta_type        : ${params.fasta_type}
group_distance    : ${params.group_distance}
min_alignment_len : ${params.min_alignment_len}
outdir            : ${params.outdir}

--

Run as            : ${workflow.commandLine}
Started at        : ${workflow.start}
Config files      : ${workflow.configFiles}

--
"""
// container images : ${workflow.containerEngine}:${workflow.container}

/*
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    IMPORT FUNCTIONS / MODULES / SUBWORKFLOWS / WORKFLOWS
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*/

import groovy.json.JsonOutput
// Main workflow
include { EXSCAN } from './workflows/exscan'

/*
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    FUNCTIONS
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*/

// DESC: Validate input arguments and initialize pipeline, printing a small summary
// ARGS: None, uses variables defined at the beginning of the script
// OUTS: `$init_summary` as log message at `INFO` level
//       `$help_message` as stdout if `--help` flag is set
//       `$version` as stdout if `--version` flag is set
//       Proper error message and exit code if required arguments are missing
// RETS: None
def validateParams() {

    // `--help` and `--version` flags
    if (params.help) {
        println help_message
        System.exit(0)
    }
    if (params.version) {
        println "${params.manifest.name} v${params.manifest.version}"
        System.exit(0)
    }

    // Check required arguments
    if (params.fasta == null) {
        println help_message
        log.error "Missing required argument: --fasta"
        System.exit(1)
    }
    if (!file(params.fasta).exists()) {
        log.error "File not found: ${params.fasta}"
        System.exit(1)
    }

    if (params.hmmdb == null) {
        println help_message
        log.error "Missing required argument: --hmmdb"
        System.exit(1)
    }
    if (!file(params.hmmdb).exists()) {
        log.error "File not found: ${params.hmmdb}"
        System.exit(1)
    }

    if (params.fasta_type != 'dna' && params.fasta_type != 'rna' && params.fasta_type != 'protein') {
        log.error "Invalid fasta type: ${params.fasta_type}. Must be one of {dna, rna, protein}"
        System.exit(1)
    }

}


// DESC: Handle hmmdb appropriately so it can be mounted correctly
// ARGS: None, uses variables defined at the beginning of the script
// OUTS: `$params.hmmdb_file` and `$params.hmmdb_dir` as new variables
// RETS: None
def handle_hmmdb() {
    // hmmscan needs access to the files generated by hmmpress,
    // but accepts the hmmdb file as input.
    // When using docker for example, if we only mount the hmmdb file,
    // hmmscan will not be able to find the index files.
    // To solve this, we mount the directory containing the hmmdb file
    // and pass the hmmdb file as input to hmmscan.
    params.hmmdb_file = params.hmmdb.split('/').last()
    params.hmmdb_dir = file(params.hmmdb).getParent()
}


// DESC: Dump versions of all tools used in the pipeline, as well as input parameters
// ARGS: None, uses variables defined at the beginning of the script
// OUTS: Versions of all tools used in the pipeline at `${params.outdir}/pipeline_info/versions.yml`
//       Input parameters at `${params.outdir}/pipeline_info/params.json`
// RETS: None
def dumpPipelineInfo() {
    ch_versions.collectFile(
        storeDir: "${params.outdir}/pipeline_info/",
        name: 'versions.yml',
        sort: true,
        newLine: true
    )


    echo ${JsonOutput.toJson(params)} > "${params.outdir}/pipeline_info/params.json"
}


// DESC: Display completion message based on workflow status
// ARGS: None, uses variables defined at the beginning of the script
// OUTS: Completion message at `INFO` or `ERROR` level
// RETS: None
def completionMsg() {

    if (workflow.success) {
        if (workflow.stats.ignoredCount == 0) {
            log.info """
Pipeline completed successfully!
            """
        }
        else {
            log.info """
Pipeline completed successully, but with erroed processes
            """
        }
    }
    else {
        log.error """
Pipeline completed with errors
        """
    }

}


/*
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    RUN MAIN WORKFLOW
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*/


workflow {

    main:

    // Validate input parameters
    validateParams()
    // Handle hmm database paths
    handle_hmmdb()
    // Initialization Summary - Everything looks good so far
    log.info init_summary




    ch_versions = Channel.empty()
    // WORKFLOW: After validation, main workflow is launched here
    EXSCAN(
        params.fasta,
        params.hmmdb_file,
        params.hmmdb_dir,
        params.dom_ieval,
        params.fasta_type,
        params.group_distance,
        params.min_alignment_len,
        ch_versions
    )
    ch_versions = ch_versions.mix(EXSCAN.out.versions)




    // Save versions of all tools used in the pipeline
    ch_versions.collectFile(
        storeDir: "${params.outdir}/pipeline_info/",
        name: 'versions.yml',
        sort: true,
        newLine: true
    )

    // Display any error encountered during the workflow
    workflow.onComplete {
        completionMsg()
    }
}
